### ISSUE TITLE
Unhandled runtime error: process is not defined (using Pexels with Gatsby)

### ISSUE THREAD

**Issue by nourmalaeb** [pexels/pexels-javascript#14]
Hello! I'm using the Pexels API in a Gatsby site. I am [migrating from Gatsby v2 to v3](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/), and I am now getting a runtime error which seems to be caused by the Pexels package.

<img width="999" alt="Screen Shot 2021-04-19 at 9 57 24 AM" src="https://user-images.githubusercontent.com/2767880/115248753-f606bb00-a0f5-11eb-9650-c6d2a2268b07.png">

Am I right in thinking it's something with the Pexels package? Should I revert to a previous version of it?

**Comment by josephfarina** [comment]
Hey @nourmalaeb, it's hard to say for sure with this information, but I don't think the new version of `pexels-javascript` would cause this issue since it was mostly additive.

There is a possibility that something went wrong in the bundle step. Would you mind reverting to version 1.0.0 or 1.0.1 and letting me know if you see the same error?

**Comment by josephfarina** [comment]
Closing because this seems to be a Gatsby specific issue: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#process-is-not-defined
