### ISSUE TITLE
Firefox and Safari: CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by murtuzamacdev** [pexels/pexels-javascript#19]
On Firefox and Safari, getting error saying:

_‘Access-Control-Allow-Origin’ missing_

**Comment by nikhilkgupta01** [comment]
Could someone look into this? Also the URL that is being used during the API call is 

> https://api.pexels.com/v1// 

instead of 

> https://api.pexels.com/v1/

**Comment by sh4d0v1** [comment]
I have the same issue.

Might be this:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#requests_with_credentials
"When responding to a credentialed request, the server must specify an origin in the value of the Access-Control-Allow-Origin header, instead of specifying the "*" wildcard."

Strange thing is, the initial requests fail (preflight and main request), but if I repeat them via dev console they work, the GET request even without preflight.

**Comment by josephfarina** [comment]
Thank you for reporting this. We are looking into it now and I will update when there is news.

**Comment by dvandersluis** [comment]
@murtuzamacdev @nikhilkgupta01 @sh4d0v1 does this issue happen for you for specific endpoints? Is it for photos, videos or both?

**Comment by murtuzamacdev** [comment]
Its the basic photo search.

`client.photos.search({ query, per_page: 1 }).then(photos => {...});`

**Comment by dvandersluis** [comment]
@murtuzamacdev can you confirm if it works today? And if a video search works?

**Comment by sh4d0v1** [comment]
I can confirm it works now, at least for images.

**Comment by dvandersluis** [comment]
@sh4d0v1 thanks! If you wouldn't mind, please test out some of the other functions and let us know. I'll keep this open for a bit to track but hopefully we've resolved the issues now!

**Comment by dvandersluis** [comment]
I am going to close this issue now as we have not received any further reports. Please feel free to add to this issue or create a new one if a problem re-emerges.
