### ISSUE TITLE
Query by user profile photos

### ISSUE THREAD

**Issue by ishaileshmishra** [pexels/pexels-javascript#4]
Please help me, How can I query photos by specific user profile. ?

Like, Get all photos by user ABC
`https://api.pexels.com/v1/search?query=user_profile`

**Comment by sno2** [comment]
Hey, it looks like they are (rightfully) hiding this method and just loading a generated JS file that injects the IMG tags for each user image.  Check out [this example](https://www.pexels.com/@wildlittlethingsphoto?format=js&seed=&page=2&type=) for the JS file used to get all photos from [@wildlittlethingsphoto](https://www.pexels.com/@wildlittlethingsphoto).  They probably don't want people being able to get user photos/videos because they could then replicate Pexel's behavior quite easily.

**Comment by josephfarina** [comment]
Hello, yes sorry we don't have this on our roadmap. Thanks for creating the issue.
